name: Deploy Flutter Web to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --release
      # - run: flutter build web --release --base-href /planetx_client/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.XPLANET_GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: planetx-online.top