name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: "Flutter version to use, empty for latest"
        required: false
        default: ""
      platforms:
        description: "Platforms to build for"
        required: true
        type: choice
        options:
          - "windows"
          - "android"
          - "all"
        default: "windows"
  push:
    tags:
      - "v[0-9]+.*"

env:
  FLUTTER_VERSION: ${{ github.event.inputs.flutter_version }}

jobs:
  build-windows:
    runs-on: windows-latest
    if: contains(github.event.inputs.platforms, 'windows') || contains(github.event.inputs.platforms, 'all') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Figure out DIR
        run: |
          $ref="${{ github.ref_name }}"
          Write-Output "ref: $ref"
          if ( "${{ github.ref_type }}".Equals("tag") ) {
              $ref=$ref.Substring(1)
          }
          "DIR=$ref" >> $env:GITHUB_ENV
          
      - name: Use the DIR
        run: |
          Write-Output "$env:DIR"
          Write-Output ${{ env.DIR }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter --version

      - name: Flutter build windows
        id: build-app
        run: |
          $version_str=$(gc .\pubspec.yaml | select-string '(?<=^version: ).*' -AllMatches | Select-Object -Expand Matches | %{$_.Value})
          $version=$version_str.Split("+")[0]
          $build_number=$version_str.Split("+")[1]
          flutter build windows --release --dart-define="APP_VERSION=$version" --dart-define="APP_BUILD_NUMBER=$build_number"

      - name: Build Inno Installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "windows_inno_setup.iss"
        shell: cmd

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xplanet_desktop_windows_setup.exe.zip
          path: build/xplanet_desktop_windows_setup.exe

      - name: Upload windows setup exe to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.XPLANET_GITHUB_TOKEN }}
          file: build/xplanet_desktop_windows_setup.exe
          asset_name: xplanet_desktop_windows_setup.exe
          tag: ${{ github.ref }}
          overwrite: true      

  build-android:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.platforms, 'android') || contains(github.event.inputs.platforms, 'all') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Figure out DIR
        run: |
          ref="${{ github.ref_name }}"
          echo "ref: $ref"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            ref=${ref#v}
          fi
          echo "DIR=${ref}" >> "$GITHUB_ENV"

      - name: Use the DIR
        run: |
          echo $DIR
          echo ${{ env.DIR }}

      - name: Decode keystore file
        env:
          XPLANET_KEYSTORE_FILE_BASE64: ${{ secrets.XPLANET_KEYSTORE_FILE_BASE64 }}
        run: echo $XPLANET_KEYSTORE_FILE_BASE64 | base64 --decode > android/app/xplanet_release.jks

      - name: temp debug
        env:
          XPLANET_KEY_PASSWORD: ${{ secrets.XPLANET_KEY_PASSWORD }}
        run: |
          md5sum android/app/xplanet_release.jks

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter --version

      - name: Flutter build apk
        env:
          XPLANET_KEY_PASSWORD: ${{ secrets.XPLANET_KEY_PASSWORD }}
        run: |
          version_str=$(cat pubspec.yaml | grep 'version: ' | sed 's/version: //')
          version_number=$(echo $version_str | cut -d'+' -f1)
          build_number=$(echo $version_str | cut -d'+' -f2)
          flutter build apk --release --dart-define="APP_VERSION=$version_number" --dart-define="APP_BUILD_NUMBER=$build_number"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xplanet.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.XPLANET_GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app-release.apk
          asset_name: xplanet.apk
          tag: ${{ github.ref }}
          overwrite: true
